config/routes.rb
Rails.application.routes.draw do
  root 'widgets#index'
  resources :widgets, :users
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  post 'change_password', to: 'users#change_password'
  post 'reset_password', to: 'users#reset_password'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from URI::InvalidURIError,
              RestClient::UnprocessableEntity, with: :common_errors

  rescue_from RestClient::Unauthorized, with: :common_errors

  private

  def authenticate_user
    redirect_to(root_path, alert_notification_text('Please signup/login to continue.')) && return unless session[:access_token]
  end

  def unauthorized_error
    redirect_to root_path, alert: 'Please re-login to continue.'
    true
  end

  def common_errors
    redirect_to root_path, alert_notification_text
    true
  end

  def alert_notification_text(txt = "Can't process request right now")
    { alert: txt }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include User
  include Authentication

  before_action :authenticate_user, only: [:show]

  def show
    @user = user
    @widgets = user_widgets
  end

  def create
    @user = create_user
    if @user
      redirect_to user_path(@user['id']), notice: 'Signup done!!!'
    else
      redirect_to root_path, alert_notification_text
    end
  end

  def login
    alert_notice = user_login ? { notice: 'Login done!!!' } : alert_notification_text
    redirect_to root_path, alert_notice
  end

  def logout
    alert_notice = user_logout ? { notice: 'Logout successfully!!!' } : alert_notification_text
    redirect_to root_path, alert_notice
  end

  def reset_password
    txt = reset_user_password
    alert_notice = txt ? { notice: txt } : alert_notification_text
    redirect_to root_path, alert_notice
  end

  def change_password
    alert_notice = change_user_password ? { notice: 'Password changed!!!' } : alert_notification_text
    redirect_to root_path, alert_notice
  end

  private

  def user_params
    params.fetch(:user, {}).permit(:first_name, :last_name, :email, :password, :image_url, :current_password, :new_password)
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  include User
  include Authentication
  include Widget

  before_action :authenticate_user, only: %i[create update edit destroy new]

  def index
    @widgets = if params[:me].to_s == 'true'
                 @my_widgets = true
                 current_user_widgets
               else
                 public_widgets
               end
  end

  def new; end

  def create
    create_widget
    redirect_to widgets_path(me: true), notice: 'Widget created successfully.'
  end

  def update
    update_widget
    redirect_to widgets_path(me: true), notice: 'Widget updated successfully.'
  end

  def edit
    @widget = params[:widget]
  end

  def destroy
    remove_widget
    redirect_to root_path(me: true), notice: 'Widget removed successfully.'
  end

  private

  def widget_params
    params.fetch(:widget, {}).permit(:name, :id, :description, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" id="mainNavIn">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger text-uppercase" data-toggle="tooltip" href="<%= root_path %>" name="Go To Home">Widgets enlists</a>
    <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right" data-target="#navbarResponsive" data-toggle="collapse" type="button">
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">
        <% if session[:access_token].nil? %>
          <li class="nav-item">
            <%= link_to "Signup", '#', class: "nav-link", data: {toggle: "modal", target: "#new_registration"} %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", '#', class: "nav-link", data: {toggle: "modal", target: "#login"} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "My widgets", widgets_path(me: true), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :post, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Reset password", '#', class: "nav-link", data: {toggle: "modal", target: "#reset_password"} %>
          </li>
          <li class="nav-item">
            <%= link_to "Change password", '#', class: "nav-link", data: {toggle: "modal", target: "#change_password"} %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%= render partial: 'users/new' %>

app/views/layouts/_notification_bar.html.erb
<%if notice.present?%>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <p id="notice"><%= notice %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif alert.present?%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <p id="alert"><%= alert %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WidgetEnlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="row">
    <div class="d-block">
      <%= render partial: 'layouts/navbar' %>
    </div>
    <div class="container d-block mt-5 pt-4">
      <%= render partial: 'layouts/notification_bar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_new.html.erb
<div class="modal fade" id="new_registration" role="dialog">
  <div class="modal-dialog modal-md pt-5">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">SignUp</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_with(url: users_path, method: "post", remote: false) do %>
          <div class="form-group">
            <%= email_field_tag "user[email]", "", class: "form-control", placeholder: "Email", required: true %>
          </div>
          <div class="form-group">
            <%= password_field_tag "user[password]", "", class: "form-control", placeholder: "Password", required: true %>
          </div>
          <div class="form-group">
            <%= text_field_tag "user[first_name]", "", class: "form-control", placeholder: "First Name", required: true %>
          </div>
          <div class="form-group">
            <%= text_field_tag "user[last_name]", "", class: "form-control", placeholder: "Last Name", required: true %>
          </div>
          <div class="form-group">
            <%= text_field_tag "user[image_url]", "", class: "form-control", placeholder: "Image URL", required: true %>
          </div>
          <%= submit_tag "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="login" role="dialog">
  <div class="modal-dialog modal-md pt-5">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Login</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_with(url: login_path, method: "post", remote: false) do %>
          <div class="form-group">
            <label>Email</label>
            <%= email_field_tag "user[email]", "", class: "form-control", placeholder: "Email", required: true %>
          </div>
          <div class="form-group">
            <label>Password</label>
            <%= password_field_tag "user[password]", "", class: "form-control", placeholder: "Password", required: true %>
          </div>
          <%= submit_tag "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="change_password" role="dialog">
  <div class="modal-dialog modal-md pt-5">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Reset password</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_with(url: change_password_path, method: "post", remote: false) do %>
          <div class="form-group">
            <label>Current Password</label>
            <%= password_field_tag "user[current_password]", "", class: "form-control", placeholder: "Current password", required: true %>
          </div>
          <div class="form-group">
            <label>New Password</label>
            <%= password_field_tag "user[new_password]", "", class: "form-control", placeholder: "New password", required: true %>
          </div>
          <%= submit_tag "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="reset_password" role="dialog">
  <div class="modal-dialog modal-md pt-5">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Reset password</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_with(url: reset_password_path, method: "post", remote: false) do %>
          <div class="form-group">
            <label>Email</label>
            <%= email_field_tag "user[email]", "", class: "form-control", placeholder: "Email", required: true %>
          </div>
          <%= submit_tag "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<div class="row">
  <h1 class="text-center col-md-12">
    <img src="<%= @user['images']['small_url']%>" width="36px">
    <%= @user['name']&.titleize %>
  </h1>
</div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
  </tr>
  </thead>
  <tbody class="js-widget-list">
    <%= render partial: 'widgets/widget_list', locals: { widgets: @widgets, user_view: true } %>
  </tbody>
</table>


<br>

app/views/widgets/_search.html.erb
<%= form_with(url: widgets_path, method: "get", class: "form-inline") do |f| %>
  <div class="form-group ml-5 mb-4">
    <%= text_field_tag 'term', '', class: "form-control", placeholder: "Enter the search term..." %>
    <%= hidden_field_tag 'me', @my_widgets %>
    <%= submit_tag "Search", class: 'ml-3 btn btn-primary' %>
  </div>
<% end %>

app/views/widgets/_widget_list.html.erb
<% if widgets.blank? %>
  <tr>
    <td>No data found!!!</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% else %>
  <% widgets.each do |widget| %>
    <% user = widget['user'] %>
    <tr>
      <td>
        <%= widget['id'] %>
      </td>
      <td>
        <%= widget['name']&.titleize %>
      </td>
      <td>
        <%= widget['description'] %>
      </td>
      <% if local_assigns[:my_widgets] %>
        <td><%= widget['kind'] %></td>
        <td class="d-flex">
          <%= link_to 'Edit', edit_widget_path(widget['id'], widget:  widget), class: 'btn btn-primary' %>
          <%= link_to 'Remove', widget_path(widget['id']), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-2 btn btn-secondary' %>
        </td>
      <% elsif !local_assigns[:user_view] %>
        <td>
          <%= image_tag(user['images']['small_url'], width: '26') %>
          <%= link_to user['name']&.titleize, user_path(user['id']) %>
        </td>
      <% end %>
    </tr>
  <% end %>
<% end %>

app/views/widgets/edit.html.erb
<h1>Edit <b><%= @widget[:name] %></b></h1>
<%= form_with(url: widget_path(id: @widget[:id]), method: 'put') do |f| %>
  <div class='form-group'>
    <label>Name</label>
    <%= text_field_tag 'widget[name]', @widget[:name], class: 'form-control', placeholder: 'Name', required: true %>
  </div>
  <div class='form-group'>
    <label>Description</label>
    <%= text_area_tag 'widget[description]', @widget[:description], class: 'form-control', placeholder: 'Description', required: true %>
  </div>
  <div class='form-group'>
    <label>Kind</label>
    <%= select_tag 'widget[kind]',
                   options_for_select([ 'hidden', 'visible' ], @widget[:kind]),
                   class: 'form-control' %>
  </div>
  <%= submit_tag 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', root_path(me: true), class: 'btn btn-secondary' %>
<% end %>

app/views/widgets/index.html.erb
<div class="d-flex">
  <h1 class="mr-auto text-uppercase">Widgets</h1>
  <div>
    <%= render partial: 'search' %>
  </div>
  <% if session[:access_token] %>
    <div>
      <%= link_to 'New widget', new_widget_path, class: 'ml-2 btn btn-secondary' %>
    </div>
  <% end %>
</div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <% if @my_widgets %>
      <th scope="col">Kind</th>
      <th scope="col">Action</th>
    <% else %>
      <th scope="col">User</th>
    <% end %>
  </tr>
  </thead>
  <tbody class="js-widget-list">
    <%= render partial: 'widget_list', locals: { widgets: @widgets, user_view: false, my_widgets: @my_widgets } %>
  </tbody>
</table>


<br>

app/views/widgets/index.js.erb
$('.js-widget-list').html("<%= escape_javascript(render 'widgets/widget_list', widgets: @widgets, my_widgets: @my_widgets, layout: false) %>");

app/views/widgets/new.html.erb
<h1>New widget</h1>
<%= form_with(url: widgets_path, method: 'post') do |f| %>
  <div class='form-group'>
    <label>Name</label>
    <%= text_field_tag 'widget[name]', '', class: 'form-control', placeholder: 'Name', required: true %>
  </div>
  <div class='form-group'>
    <label>Description</label>
    <%= text_area_tag 'widget[description]', '', class: 'form-control', placeholder: 'Description', required: true %>
  </div>
  <div class='form-group'>
    <label>Kind</label>
    <%= select_tag 'widget[kind]',
                   options_for_select([ 'visible', 'hidden' ], nil),
                   class: 'form-control' %>
  </div>
  <%= submit_tag 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', root_path(me: true), class: 'btn btn-secondary' %>
<% end %>